# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://lecarver.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Lester Carver
author-bio: GIS Specialist. Telling Stories. Making Data Accessible  # change to false to hide
author-image: headshot.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/lecarver
linkedin: https://www.linkedin.com/in/lester-carver/
medium: false
google-scholar: false
email: mailto:lester.e.carver@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
